---
abstract: 'Perl implementation of GNTP Protocol (Client Part)'
author:
  - 'Yasuhiro Matsumoto <mattn.jp@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.48
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GNTP-Growl
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Crypt::CBC: 2.29
  Data::UUID: 0.149
  Digest::MD5: 2.36
  Digest::SHA: 5.45
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
